### ISSUE TITLE
live match controller not working

### ISSUE THREAD

**Issue by Johann150** [ivanseidel/TournamenterApp#16]
when I try to start the live match controller, I just get

> # Oops. 404 - Not found
> The page you were looking for could not be found.
> Url: /matches/live/3
> Method: GET

I have put the respective match to `playing` instead of `sheduled`

**Comment by Johann150** [comment]
Not sure if this belongs to this repo or if I should post this in the tournamenter repo

**Comment by ivanseidel** [comment]
Hi Johann!
Thanks for the PR. Yes, its best if you submit it to /Tournamenter. That bug is unrelated with the UI (this repo)

Also, can you try and fix it as well? Im not sure if it was 100% implemented.

(closing, but please re open it there)
